export default {
  GET_GROUPS: 'EVENT_GET_GROUPS',
  GET_SERIES: 'EVENT_GET_SERIES',
  GET_GROUP_FILTERS: 'EVENT_GET_GROUP_FILTERS',
  API_SET_VALUE: 'EVENT_API_SET_VALUE',
  LOGIN: 'EVENT_LOGIN',
  LOGIN_IMAGE: 'EVENT_LOGIN_IMAGE',
  EXIT: 'EXIT',
  WINDOW_MAXIMIZE: 'WINDOW_MAXIMIZE',
  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
  GET_DASHBOARD: 'EVENT_GET_DASHBOARD',
  GET_FILE_RECENT: 'EVENT_GET_FILE_RECENT',
  OPEN_EXTERNAL: 'EVENT_OPEN_EXTERNAL',
  GET_SERIES_RECENT: 'EVENT_GET_SERIES_RECENT',
  GET_SERIES_CALENDAR: 'EVENT_GET_SERIES_CALENDAR'
};
